In [81]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

%precision %.9f
np.set_printoptions(suppress=True, precision=9)
pd.set_option('display.float_format', lambda x: f'{x:.9f}')

In [82]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'

In [83]:
df = pd.read_csv(data)
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.850000000,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.950000000,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.850000000,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.300000000,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.700000000,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.800000000,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.200000000,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.600000000,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.400000000,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.650000000,6844.5,No

In [84]:
# as there are lot of columns so we are not able to see all of them
# in order to see them what we will do is basically take a transpose
# so that columns come on the vertical left side instead of the present horizontal top line
df.T

,0,1,2,3,4,5,6,7,8,9,...,7033,7034,7035,7036,7037,7038,7039,7040,7041,7042
customerID,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU,9305-CDSKC,1452-KIOVK,6713-OKOMC,7892-POOKP,6388-TABGU,...,9767-FFLEM,0639-TSIQW,8456-QDAVC,7750-EYXWZ,2569-WGERO,6840-RESVB,2234-XADUH,4801-JZAZL,8361-LTMKD,3186-AJIEK
gender,Female,Male,Male,Male,Female,Female,Male,Female,Female,Male,...,Male,Female,Male,Female,Female,Male,Female,Female,Male,Male
SeniorCitizen,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
Partner,Yes,No,No,No,No,No,No,No,Yes,No,...,No,No,No,No,No,Yes,Yes,Yes,Yes,No
Dependents,No,No,No,No,No,No,Yes,No,No,Yes,...,No,No,No,No,No,Yes,Yes,Yes,No,No
tenure,1,34,2,45,2,8,22,10,28,62,...,38,67,19,12,72,24,72,11,4,66
PhoneService,No,Yes,Yes,No,Yes,Yes,Yes,No,Yes,Yes,...,Yes,Yes,Yes,No,Yes,Yes,Yes,No,Yes,Yes
MultipleLines,No phone service,No,No,No phone service,No,Yes,Yes,No phone service,Yes,No,...,No,Yes,No,No phone service,No,Yes,Yes,No phone service,Yes,No
InternetService,DSL,DSL,DSL,DSL,Fiber optic,Fiber optic,Fiber optic,DSL,Fiber optic,DSL,...,Fiber optic,Fiber optic,Fiber optic,DSL,No,DSL,Fiber optic,DSL,Fiber optic,Fiber optic
OnlineSecurity,No,Yes,Yes,Yes,No,No,No,Yes,No,Yes,...,No,Yes,No,No,No internet service,Yes,No,Yes,No,Yes
OnlineBackup,Yes,No,Yes,No,No,No,Yes,No,No,Yes,...,No,Yes,No,Yes,No internet service,No,Yes,No,No,No
DeviceProtection,No,Yes,No,Yes,No,Yes,No,No,Yes,No,...,No,Yes,No,Yes,No internet service,Yes,Yes,No,No,Yes
TechSupport,No,No,No,Yes,No,No,No,No,Yes,No,...,No,No,No,Yes,No internet service,Yes,No,No,No,Yes
StreamingTV,No,No,No,No,No,Yes,Yes,No,Yes,No,...,No,Yes,Yes,Yes,No internet service,Yes,Yes,No,No,Yes
StreamingMovies,No,No,No,No,No,Yes,No,No,Yes,No,...,No,No,No,Yes,No internet service,Yes,Yes,No,No,Yes
Contract,Month-to-month,One year,Month-to-month,One year,Month-to-month,Month-to-month,Month-to-month,Month-to-month,Month-to-month,One year,...,Month-to-month,Month-to-month,Month-to-month,One year,Two year,One year,One year,Month-to-month,Month-to-month,Two year
PaperlessBilling,Yes,No,Yes,No,Yes,Yes,Yes,No,Yes,No,...,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes
PaymentMethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check,Electronic check,Credit card (automatic),Mailed check,Electronic check,Bank transfer (automatic),...,Credit card (automatic),Credit card (automatic),Bank transfer (automatic),Electronic check,Bank transfer (automatic),Mailed check,Credit card (automatic),Electronic check,Mailed check,Bank transfer (automatic)
MonthlyCharges,29.850000000,56.950000000,53.850000000,42.300000000,70.700000000,99.650000000,89.100000000,29.750000000,104.800000000,56.150000000,...,69.500000000,102.950000000,78.700000000,60.650000000,21.150000000,84.800000000,103.200000000,29.600000000,74.400000000,105.650000000
TotalCharges,29.85,1889.5,108.15,1840.75,151.65,820.5,1949.4,301.9,3046.05,3487.95,...,2625.25,6886.25,1495.1,743.3,1419.4,1990.5,7362.9,346.45,306.6,6844.5
Churn,No,No,Yes,No,Yes,Yes,No,No,Yes,No,...,No,Yes,No,No,No,No,No,No,Yes,No

In [85]:
df.columns = df.columns.str.lower().str.replace(' ','_')

catgorical_columns = list(df.dtypes[df.dtypes == 'str'].index)

for c in catgorical_columns:
    df[c] = df[c].str.lower().str.replace(' ','_')

In [86]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,7033,7034,7035,7036,7037,7038,7039,7040,7041,7042
customerid,7590-vhveg,5575-gnvde,3668-qpybk,7795-cfocw,9237-hqitu,9305-cdskc,1452-kiovk,6713-okomc,7892-pookp,6388-tabgu,...,9767-fflem,0639-tsiqw,8456-qdavc,7750-eyxwz,2569-wgero,6840-resvb,2234-xaduh,4801-jzazl,8361-ltmkd,3186-ajiek
gender,female,male,male,male,female,female,male,female,female,male,...,male,female,male,female,female,male,female,female,male,male
seniorcitizen,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
partner,yes,no,no,no,no,no,no,no,yes,no,...,no,no,no,no,no,yes,yes,yes,yes,no
dependents,no,no,no,no,no,no,yes,no,no,yes,...,no,no,no,no,no,yes,yes,yes,no,no
tenure,1,34,2,45,2,8,22,10,28,62,...,38,67,19,12,72,24,72,11,4,66
phoneservice,no,yes,yes,no,yes,yes,yes,no,yes,yes,...,yes,yes,yes,no,yes,yes,yes,no,yes,yes
multiplelines,no_phone_service,no,no,no_phone_service,no,yes,yes,no_phone_service,yes,no,...,no,yes,no,no_phone_service,no,yes,yes,no_phone_service,yes,no
internetservice,dsl,dsl,dsl,dsl,fiber_optic,fiber_optic,fiber_optic,dsl,fiber_optic,dsl,...,fiber_optic,fiber_optic,fiber_optic,dsl,no,dsl,fiber_optic,dsl,fiber_optic,fiber_optic
onlinesecurity,no,yes,yes,yes,no,no,no,yes,no,yes,...,no,yes,no,no,no_internet_service,yes,no,yes,no,yes
onlinebackup,yes,no,yes,no,no,no,yes,no,no,yes,...,no,yes,no,yes,no_internet_service,no,yes,no,no,no
deviceprotection,no,yes,no,yes,no,yes,no,no,yes,no,...,no,yes,no,yes,no_internet_service,yes,yes,no,no,yes
techsupport,no,no,no,yes,no,no,no,no,yes,no,...,no,no,no,yes,no_internet_service,yes,no,no,no,yes
streamingtv,no,no,no,no,no,yes,yes,no,yes,no,...,no,yes,yes,yes,no_internet_service,yes,yes,no,no,yes
streamingmovies,no,no,no,no,no,yes,no,no,yes,no,...,no,no,no,yes,no_internet_service,yes,yes,no,no,yes
contract,month-to-month,one_year,month-to-month,one_year,month-to-month,month-to-month,month-to-month,month-to-month,month-to-month,one_year,...,month-to-month,month-to-month,month-to-month,one_year,two_year,one_year,one_year,month-to-month,month-to-month,two_year
paperlessbilling,yes,no,yes,no,yes,yes,yes,no,yes,no,...,yes,yes,yes,no,yes,yes,yes,yes,yes,yes
paymentmethod,electronic_check,mailed_check,mailed_check,bank_transfer_(automatic),electronic_check,electronic_check,credit_card_(automatic),mailed_check,electronic_check,bank_transfer_(automatic),...,credit_card_(automatic),credit_card_(automatic),bank_transfer_(automatic),electronic_check,bank_transfer_(automatic),mailed_check,credit_card_(automatic),electronic_check,mailed_check,bank_transfer_(automatic)
monthlycharges,29.850000000,56.950000000,53.850000000,42.300000000,70.700000000,99.650000000,89.100000000,29.750000000,104.800000000,56.150000000,...,69.500000000,102.950000000,78.700000000,60.650000000,21.150000000,84.800000000,103.200000000,29.600000000,74.400000000,105.650000000
totalcharges,29.85,1889.5,108.15,1840.75,151.65,820.5,1949.4,301.9,3046.05,3487.95,...,2625.25,6886.25,1495.1,743.3,1419.4,1990.5,7362.9,346.45,306.6,6844.5
churn,no,no,yes,no,yes,yes,no,no,yes,no,...,no,yes,no,no,no,no,no,no,yes,no

In [87]:
# Less check the types of columns
df.dtypes

customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges            str
churn                   str
dtype: object

In [88]:
# As we can see above totalcharges is shown as str when it should be an integer
# so less investigate behind the scenes
# pd.to_numeric(df.totalcharges)

In [89]:
tc = pd.to_numeric(df.totalcharges, errors = 'coerce')
# here were replace unparseable string with Nan

In [90]:
df[tc.isnull()][['customerid','totalcharges','tenure']]

      customerid totalcharges  tenure
488   4472-lvygi            _       0
753   3115-czmzd            _       0
936   5709-lvoeq            _       0
1082  4367-nuyao            _       0
1340  1371-dwpaz            _       0
3331  7644-omvmy            _       0
3826  3213-vvolg            _       0
4380  2520-sgtta            _       0
5218  2923-arzlg            _       0
6670  4075-wkniu            _       0
6754  2775-sefee            _       0

In [91]:
# here are 11 customers whose tenure is 0 which means these
# are new customers who have just opened their account 
# ans so have no balance which we can see below too
df[df.tenure==0]

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
488,4472-lvygi,female,0,yes,yes,0,no,no_phone_service,dsl,yes,...,yes,yes,yes,no,two_year,yes,bank_transfer_(automatic),52.550000000,_,no
753,3115-czmzd,male,0,no,yes,0,yes,no,no,no_internet_service,...,no_internet_service,no_internet_service,no_internet_service,no_internet_service,two_year,no,mailed_check,20.250000000,_,no
936,5709-lvoeq,female,0,yes,yes,0,yes,no,dsl,yes,...,yes,no,yes,yes,two_year,no,mailed_check,80.850000000,_,no
1082,4367-nuyao,male,0,yes,yes,0,yes,yes,no,no_internet_service,...,no_internet_service,no_internet_service,no_internet_service,no_internet_service,two_year,no,mailed_check,25.750000000,_,no
1340,1371-dwpaz,female,0,yes,yes,0,no,no_phone_service,dsl,yes,...,yes,yes,yes,no,two_year,no,credit_card_(automatic),56.050000000,_,no
3331,7644-omvmy,male,0,yes,yes,0,yes,no,no,no_internet_service,...,no_internet_service,no_internet_service,no_internet_service,no_internet_service,two_year,no,mailed_check,19.850000000,_,no
3826,3213-vvolg,male,0,yes,yes,0,yes,yes,no,no_internet_service,...,no_internet_service,no_internet_service,no_internet_service,no_internet_service,two_year,no,mailed_check,25.350000000,_,no
4380,2520-sgtta,female,0,yes,yes,0,yes,no,no,no_internet_service,...,no_internet_service,no_internet_service,no_internet_service,no_internet_service,two_year,no,mailed_check,20.000000000,_,no
5218,2923-arzlg,male,0,yes,yes,0,yes,no,no,no_internet_service,...,no_internet_service,no_internet_service,no_internet_service,no_internet_service,one_year,yes,mailed_check,19.700000000,_,no
6670,4075-wkniu,female,0,yes,yes,0,yes,yes,dsl,no,...,yes,yes,yes,no,two_year,no,mailed_check,73.350000000,_,no
6754,2775-sefee,male,0,no,yes,0,yes,yes,dsl,yes,...,no,yes,no,no,two_year,yes,bank_transfer_(automatic),61.900000000,_,no

In [92]:
df.totalcharges = pd.to_numeric(df.totalcharges, errors='coerce')
df.totalcharges = df.totalcharges.fillna(0)

In [93]:
df.churn.head()

0     no
1     no
2    yes
3     no
4    yes
Name: churn, dtype: str

In [94]:
# as we can see above churn still has strings but for classification
# wee need numbers. We compare the column with 'yes'
df.churn = (df.churn =='yes').astype(int)

In [95]:
df.churn.head()

0    0
1    0
2    1
3    0
4    1
Name: churn, dtype: int64

# Setting up the validation framework

In [96]:
from sklearn.model_selection import train_test_split

In [97]:
df_full_train, df_test = train_test_split(df,test_size=0.2,random_state=2)
# We put aside 20% data for test set

In [98]:
df_train,df_val = train_test_split(df_full_train,test_size=0.25,random_state=1)
# here we use 0.25 not 0.2 because df_full train has only 80% of original data and since
# 20% of 80 is 25% thats why 0.25
# TLDR: we put aside another 20% of original data for validation

In [99]:
len(df_train),len(df_val),len(df_test)

(4225, 1409, 1409)

In [100]:
# The full dataset has 7043 customers, 4225 for training data (60%), 1409 for validation (20%)
# and 1409 for testing (20%)
# The random_state = 1 argument fixes seed of random shufflingso that when we refresh our
# notebook we get the exactly same split

In [101]:
df_train = df_train.reset_index(drop = True)
df_val = df_val.reset_index(drop = True)
df_test = df_test.reset_index(drop = True)

In [102]:
# Isolating the target: We extract or isolate the target for this project which is churn
y_train = df_train['churn']
y_val = df_val['churn']
y_test = df_test['churn']

In [103]:
# Now we delete the column from the dataframes as we don't accidently wanna use the 
# target as feature when we train our model
del df_train['churn']
del df_val['churn']
del df_test['churn']

# Exploratory Data Analysis (EDA)

In [104]:
# In this section we will explore the training data: we check for missing values,
# look at the distribution of target variable and go through numerical and
# categorical columns
df_full_train = df_full_train.reset_index(drop=True)

In [105]:
# now we check if any of our column has missing values or Nan
df_full_train.isnull().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64

In [106]:
# Everything is 0, there is no missing values anywhere, We already took care of only 
# column that had them, totalcharges during data preparation

In [107]:
# now we look at target variable
df_full_train.churn.value_counts(normalize=True)

churn
0   0.730031949
1   0.269968051
Name: proportion, dtype: float64

In [108]:
# Looking at data, we see that 73% of customers stayed and 27% customers churned.
# The percentage of ones - 0.269968 around 27% is called churn rate

# Because churn is now a column of ones and zeros, we can also use mean. The mean
# of a binary column is number of ones divided by total number of rows,
# which is exactly the churn rate

df_full_train.churn.mean()

0.269968051

In [109]:
# Next we decide which columns are numerical and which ones are categorical
# for that we look at the data
df.T

,0,1,2,3,4,5,6,7,8,9,...,7033,7034,7035,7036,7037,7038,7039,7040,7041,7042
customerid,7590-vhveg,5575-gnvde,3668-qpybk,7795-cfocw,9237-hqitu,9305-cdskc,1452-kiovk,6713-okomc,7892-pookp,6388-tabgu,...,9767-fflem,0639-tsiqw,8456-qdavc,7750-eyxwz,2569-wgero,6840-resvb,2234-xaduh,4801-jzazl,8361-ltmkd,3186-ajiek
gender,female,male,male,male,female,female,male,female,female,male,...,male,female,male,female,female,male,female,female,male,male
seniorcitizen,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
partner,yes,no,no,no,no,no,no,no,yes,no,...,no,no,no,no,no,yes,yes,yes,yes,no
dependents,no,no,no,no,no,no,yes,no,no,yes,...,no,no,no,no,no,yes,yes,yes,no,no
tenure,1,34,2,45,2,8,22,10,28,62,...,38,67,19,12,72,24,72,11,4,66
phoneservice,no,yes,yes,no,yes,yes,yes,no,yes,yes,...,yes,yes,yes,no,yes,yes,yes,no,yes,yes
multiplelines,no_phone_service,no,no,no_phone_service,no,yes,yes,no_phone_service,yes,no,...,no,yes,no,no_phone_service,no,yes,yes,no_phone_service,yes,no
internetservice,dsl,dsl,dsl,dsl,fiber_optic,fiber_optic,fiber_optic,dsl,fiber_optic,dsl,...,fiber_optic,fiber_optic,fiber_optic,dsl,no,dsl,fiber_optic,dsl,fiber_optic,fiber_optic
onlinesecurity,no,yes,yes,yes,no,no,no,yes,no,yes,...,no,yes,no,no,no_internet_service,yes,no,yes,no,yes
onlinebackup,yes,no,yes,no,no,no,yes,no,no,yes,...,no,yes,no,yes,no_internet_service,no,yes,no,no,no
deviceprotection,no,yes,no,yes,no,yes,no,no,yes,no,...,no,yes,no,yes,no_internet_service,yes,yes,no,no,yes
techsupport,no,no,no,yes,no,no,no,no,yes,no,...,no,no,no,yes,no_internet_service,yes,no,no,no,yes
streamingtv,no,no,no,no,no,yes,yes,no,yes,no,...,no,yes,yes,yes,no_internet_service,yes,yes,no,no,yes
streamingmovies,no,no,no,no,no,yes,no,no,yes,no,...,no,no,no,yes,no_internet_service,yes,yes,no,no,yes
contract,month-to-month,one_year,month-to-month,one_year,month-to-month,month-to-month,month-to-month,month-to-month,month-to-month,one_year,...,month-to-month,month-to-month,month-to-month,one_year,two_year,one_year,one_year,month-to-month,month-to-month,two_year
paperlessbilling,yes,no,yes,no,yes,yes,yes,no,yes,no,...,yes,yes,yes,no,yes,yes,yes,yes,yes,yes
paymentmethod,electronic_check,mailed_check,mailed_check,bank_transfer_(automatic),electronic_check,electronic_check,credit_card_(automatic),mailed_check,electronic_check,bank_transfer_(automatic),...,credit_card_(automatic),credit_card_(automatic),bank_transfer_(automatic),electronic_check,bank_transfer_(automatic),mailed_check,credit_card_(automatic),electronic_check,mailed_check,bank_transfer_(automatic)
monthlycharges,29.850000000,56.950000000,53.850000000,42.300000000,70.700000000,99.650000000,89.100000000,29.750000000,104.800000000,56.150000000,...,69.500000000,102.950000000,78.700000000,60.650000000,21.150000000,84.800000000,103.200000000,29.600000000,74.400000000,105.650000000
totalcharges,29.850000000,1889.500000000,108.150000000,1840.750000000,151.650000000,820.500000000,1949.400000000,301.900000000,3046.050000000,3487.950000000,...,2625.250000000,6886.250000000,1495.100000000,743.300000000,1419.400000000,1990.500000000,7362.900000000,346.450000000,306.600000000,6844.500000000
churn,0,0,1,0,1,1,0,0,1,0,...,0,1,0,0,0,0,0,0,1,0

In [110]:
# As from above you can see seniorcitizen, tenure, monthlycharges, totalcharges
# and churn are numerical but seniorcitizen is just 0 and 1 which is 
# categorical in nature and churn is the targe
# So only tenure, monthlycharges and totalcharges are numerical

numerical = ['tenure', 'monthlycharges','totalcharges']

In [111]:
# Rest 16 columns are categorical except customer id which is just an identifier
# its useless as a feature

categorical = [
    'gender',
    'seniorcitizen',
    'partner',
    'dependents',
    'phoneservice',
    'multiplelines',
    'internetservice',
    'onlinesecurity',
    'onlinebackup',
    'deviceprotection',
    'techsupport',
    'streamingtv',
    'streamingmovies',
    'contract',
    'paperlessbilling',
    'paymentmethod',
]

In [112]:
# Less check unique values each categorical variable has
df_full_train[categorical].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

In [113]:
# most columns have 2 or 3 unique values. The number of categories matters as it 
# determines how many columns we get after one hot encoding

# Feature importance: Churn rate and risk ratio

In [114]:
# here we find out which features affect our target variable
global_churn = df_full_train.churn.mean()
global_churn

0.269968051

In [115]:
# now less look at individual variables such as gender 
churn_female = df_full_train[df_full_train.gender=='female'].churn.mean()
churn_male = df_full_train[df_full_train.gender=='male'].churn.mean()

In [116]:
churn_female, churn_male

(0.274847506, 0.265191430)

In [117]:
# as we can see from above they are quite similar to global churn rate
# even then less compute their difference
global_churn-churn_female

-0.004879455

In [118]:
global_churn-churn_male

0.004776622

In [119]:
# as we can see from above their difference is too minimal so gender is not a
# good feature
# now less look at more promising variable partner

In [120]:
df_full_train.partner.value_counts()

partner
no     2914
yes    2720
Name: count, dtype: int64

In [121]:
churn_partner = df_full_train[df_full_train.partner == 'yes'].churn.mean()
churn_no_partner = df_full_train[df_full_train.partner == 'no'].churn.mean()

In [122]:
churn_partner,churn_no_partner

(0.202941176, 0.332532601)

In [123]:
#this looks different from gender as differences are big
global_churn-churn_no_partner

-0.062564550

In [124]:
global_churn-churn_partner

0.067026875

In [125]:
# difference of 6 percent is quite something
# the larger the absolute difference the more important the variable

# Risk ratio

In [126]:
# The difference is expressed in absolute terms. The same idea can be expressed in
# relative terms as a ratio between the group churn rate and the global churn rate

In [127]:
churn_no_partner/global_churn

1.231747979

In [128]:
churn_partner/global_churn

0.751722938

In [129]:
# as we can see from above, 1.23 indicates that haveing no partner
# means group is more likely to churn

SELECT
    gender,
    AVG(churn),
    AVG(churn) - global_churn AS diff,
    AVG(churn) / global_churn AS risk
FROM
    data
GROUP BY
    gender;

In [130]:
from IPython.display import display

In [131]:
for c in categorical:
    print(c)
    df_group = df_full_train.groupby(c).churn.agg(['mean','count'])
    df_group['diff']=df_group['mean']-global_churn
    df_group['risk']=df_group['mean']/global_churn
    display(df_group)
    print()
    print()

gender

              mean  count         diff        risk
gender
female 0.274847506   2787  0.004879455 1.018074195
male   0.265191430   2847 -0.004776622 0.982306715

seniorcitizen

                     mean  count         diff        risk
seniorcitizen
0             0.240603100   4709 -0.029364951 0.891228053
1             0.419459459    925  0.149491408 1.553737406

partner

               mean  count         diff        risk
partner
no      0.332532601   2914  0.062564550 1.231747979
yes     0.202941176   2720 -0.067026875 0.751722938

dependents

                  mean  count         diff        risk
dependents
no         0.316582915   3980  0.046614863 1.172668074
yes        0.157799274   1654 -0.112168777 0.584510922

phoneservice

                    mean  count         diff        risk
phoneservice
no           0.250000000    560 -0.019968051 0.926035503
yes          0.272171857   5074  0.002203805 1.008163208

multiplelines

                        mean  count         diff        risk
multiplelines
no               0.259397097   2687 -0.010570954 0.960843685
no_phone_service 0.250000000    560 -0.019968051 0.926035503
yes              0.286552158   2387  0.016584106 1.061429885

internetservice

                       mean  count         diff        risk
internetservice
dsl             0.194099379   1932 -0.075868672 0.718971664
fiber_optic     0.423138511   2498  0.153170460 1.567365135
no              0.073920266   1204 -0.196047785 0.273811162

onlinesecurity

                           mean  count         diff        risk
onlinesecurity
no                  0.420120439   2823  0.150152388 1.556185769
no_internet_service 0.073920266   1204 -0.196047785 0.273811162
yes                 0.153080274   1607 -0.116887777 0.567031073

onlinebackup

                           mean  count         diff        risk
onlinebackup
no                  0.408667477   2469  0.138699426 1.513762369
no_internet_service 0.073920266   1204 -0.196047785 0.273811162
yes                 0.215706272   1961 -0.054261779 0.799006665

deviceprotection

                           mean  count         diff        risk
deviceprotection
no                  0.397111913   2493  0.127143862 1.470958922
no_internet_service 0.073920266   1204 -0.196047785 0.273811162
yes                 0.228187919   1937 -0.041780132 0.845240459

techsupport

                           mean  count         diff        risk
techsupport
no                  0.424447612   2806  0.154479561 1.572214232
no_internet_service 0.073920266   1204 -0.196047785 0.273811162
yes                 0.148399015   1624 -0.121569036 0.549691025

streamingtv

                           mean  count         diff        risk
streamingtv
no                  0.340151178   2249  0.070183127 1.259968270
no_internet_service 0.073920266   1204 -0.196047785 0.273811162
yes                 0.305823017   2181  0.035854966 1.132811885

streamingmovies

                           mean  count         diff        risk
streamingmovies
no                  0.340703971   2216  0.070735920 1.262015893
no_internet_service 0.073920266   1204 -0.196047785 0.273811162
yes                 0.305781391   2214  0.035813340 1.132657697

contract

                      mean  count         diff        risk
contract
month-to-month 0.436012862   3110  0.166044811 1.615053559
one_year       0.108547009   1170 -0.161421043 0.402073535
two_year       0.028064993   1354 -0.241903059 0.103956718

paperlessbilling

                        mean  count         diff        risk
paperlessbilling
no               0.165364583   2304 -0.104603468 0.612533900
yes              0.342342342   3330  0.072374291 1.268084653

paymentmethod

                                 mean  count         diff        risk
paymentmethod
bank_transfer_(automatic) 0.170809944   1247 -0.099158107 0.632704289
credit_card_(automatic)   0.150741351   1214 -0.119226700 0.558367371
electronic_check          0.457502623   1906  0.187534572 1.694654687
mailed_check              0.199684294   1267 -0.070283758 0.739658981

In [132]:
from sklearn.metrics import mutual_info_score

In [133]:
mutual_info_score(df_full_train.churn,df_full_train.contract)

0.103061737

In [134]:
mutual_info_score(df_full_train.churn,df_full_train.gender)

0.000059128

In [135]:
# contract has higher score than gender and so it matters mores in deciding whether a 
# customer will churn or not

In [136]:
def mutual_info_churn_score(series):
    return mutual_info_score(df_full_train.churn,series)

In [137]:
categorical

['gender',
 'seniorcitizen',
 'partner',
 'dependents',
 'phoneservice',
 'multiplelines',
 'internetservice',
 'onlinesecurity',
 'onlinebackup',
 'deviceprotection',
 'techsupport',
 'streamingtv',
 'streamingmovies',
 'contract',
 'paperlessbilling',
 'paymentmethod']

In [138]:
mi = df_full_train[categorical].apply(mutual_info_churn_score)
mi.sort_values(ascending = False)
#mi = mutual information

contract           0.103061737
techsupport        0.066326510
onlinesecurity     0.063907744
internetservice    0.056059477
onlinebackup       0.048986425
paymentmethod      0.044974193
deviceprotection   0.044954922
streamingmovies    0.032616292
streamingtv        0.032597806
paperlessbilling   0.020033629
dependents         0.014229851
partner            0.010757692
seniorcitizen      0.010381399
multiplelines      0.000530469
phoneservice       0.000113258
gender             0.000059128
dtype: float64

In [139]:
# As we can see above contract, techsupport, online service and one of the most important
# features which know about our target or our target has higher dependency on them than
# the rest
# Higher mutual information = stronger relationship with the target
# and usually more predictive information.

In [140]:
df_full_train[numerical].corrwith(df_full_train.churn)

tenure           -0.358017169
monthlycharges    0.193836773
totalcharges     -0.204526534
dtype: float64

In [141]:
# Tenure has medium negative correlation
# Monthly charges has low to medium positive correlation
# Total charges has low to medium negative correlation

In [142]:
# But to rank features by importance we don't care about the direction, only
# about the strength, so we take the absolute values
df_full_train[numerical].corrwith(df_full_train.churn).abs()

tenure           0.358017169
monthlycharges   0.193836773
totalcharges     0.204526534
dtype: float64

In [143]:
# Tenure is the most important numerical feature

In [144]:
# We can double check the correlation by splitting customers into groups
# and computing churn rate in each

In [145]:
df_full_train[df_full_train.tenure <= 2].churn.mean()

0.586107091

In [146]:
df_full_train[(df_full_train.tenure > 2) & (df_full_train.tenure <= 12)].churn.mean()

0.415645617

In [147]:
df_full_train[df_full_train.tenure > 12].churn.mean()

0.173879444

In [148]:
# The pattern we observe above is that customers who have been with company 
# 2 months or less have 58 % of churning, between 2 months and 12 have
# 41 % and longer than 12 months or 1 year have 17 % and it makes sense
# as we got negative correlation with tenure -0.358017169

# One hot encoding

In [149]:
# We convert dataframe into dictionaries using this
dicts = df[categorical + numerical].to_dict(orient='records')
#  The orient records argument means one dictionary per row

In [150]:
dicts

[{'gender': 'female',
  'seniorcitizen': 0,
  'partner': 'yes',
  'dependents': 'no',
  'phoneservice': 'no',
  'multiplelines': 'no_phone_service',
  'internetservice': 'dsl',
  'onlinesecurity': 'no',
  'onlinebackup': 'yes',
  'deviceprotection': 'no',
  'techsupport': 'no',
  'streamingtv': 'no',
  'streamingmovies': 'no',
  'contract': 'month-to-month',
  'paperlessbilling': 'yes',
  'paymentmethod': 'electronic_check',
  'tenure': 1,
  'monthlycharges': 29.850000000,
  'totalcharges': 29.850000000},
 {'gender': 'male',
  'seniorcitizen': 0,
  'partner': 'no',
  'dependents': 'no',
  'phoneservice': 'yes',
  'multiplelines': 'no',
  'internetservice': 'dsl',
  'onlinesecurity': 'yes',
  'onlinebackup': 'no',
  'deviceprotection': 'yes',
  'techsupport': 'no',
  'streamingtv': 'no',
  'streamingmovies': 'no',
  'contract': 'one_year',
  'paperlessbilling': 'no',
  'paymentmethod': 'mailed_check',
  'tenure': 34,
  'monthlycharges': 56.950000000,
  'totalcharges': 1889.500000000},
 {'gender': 'male',
  'seniorcitizen': 0,
  'partner': 'no',
  'dependents': 'no',
  'phoneservice': 'yes',
  'multiplelines': 'no',
  'internetservice': 'dsl',
  'onlinesecurity': 'yes',
  'onlinebackup': 'yes',
  'deviceprotection': 'no',
  'techsupport': 'no',
  'streamingtv': 'no',
  'streamingmovies': 'no',
  'contract': 'month-to-month',
  'paperlessbilling': 'yes',
  'paymentmethod': 'mailed_check',
  'tenure': 2,
  'monthlycharges': 53.850000000,
  'totalcharges': 108.150000000},
 {'gender': 'male',
  'seniorcitizen': 0,
  'partner': 'no',
  'dependents': 'no',
  'phoneservice': 'no',
  'multiplelines': 'no_phone_service',
  'internetservice': 'dsl',
  'onlinesecurity': 'yes',
  'onlinebackup': 'no',
  'deviceprotection': 'yes',
  'techsupport': 'yes',
  'streamingtv': 'no',
  'streamingmovies': 'no',
  'contract': 'one_year',
  'paperlessbilling': 'no',
  'paymentmethod': 'bank_transfer_(automatic)',
  'tenure': 45,
  'monthlycharges': 42.300000000,
  'totalcharges': 1840.750000000},
 {'gender': 'female',
  'seniorcitizen': 0,
  'partner': 'no',
  'dependents': 'no',
  'phoneservice': 'yes',
  'multiplelines': 'no',
  'internetservice': 'fiber_optic',
  'onlinesecurity': 'no',
  'onlinebackup': 'no',
  'deviceprotection': 'no',
  'techsupport': 'no',
  'streamingtv': 'no',
  'streamingmovies': 'no',
  'contract': 'month-to-month',
  'paperlessbilling': 'yes',
  'paymentmethod': 'electronic_check',
  'tenure': 2,
  'monthlycharges': 70.700000000,
  'totalcharges': 151.650000000},
 {'gender': 'female',
  'seniorcitizen': 0,
  'partner': 'no',
  'dependents': 'no',
  'phoneservice': 'yes',
  'multiplelines': 'yes',
  'internetservice': 'fiber_optic',
  'onlinesecurity': 'no',
  'onlinebackup': 'no',
  'deviceprotection': 'yes',
  'techsupport': 'no',
  'streamingtv': 'yes',
  'streamingmovies': 'yes',
  'contract': 'month-to-month',
  'paperlessbilling': 'yes',
  'paymentmethod': 'electronic_check',
  'tenure': 8,
  'monthlycharges': 99.650000000,
  'totalcharges': 820.500000000},
 {'gender': 'male',
  'seniorcitizen': 0,
  'partner': 'no',
  'dependents': 'yes',
  'phoneservice': 'yes',
  'multiplelines': 'yes',
  'internetservice': 'fiber_optic',
  'onlinesecurity': 'no',
  'onlinebackup': 'yes',
  'deviceprotection': 'no',
  'techsupport': 'no',
  'streamingtv': 'yes',
  'streamingmovies': 'no',
  'contract': 'month-to-month',
  'paperlessbilling': 'yes',
  'paymentmethod': 'credit_card_(automatic)',
  'tenure': 22,
  'monthlycharges': 89.100000000,
  'totalcharges': 1949.400000000},
 {'gender': 'female',
  'seniorcitizen': 0,
  'partner': 'no',
  'dependents': 'no',
  'phoneservice': 'no',
  'multiplelines': 'no_phone_service',
  'internetservice': 'dsl',
  'onlinesecurity': 'yes',
  'onlinebackup': 'no',
  'deviceprotection': 'no',
  'techsupport': 'no',
  'streamingtv': 'no',
  'streamingmovies': 'no',
  'contract': 'month-to-month',
  'paperlessbilling': 'no',
  'paymentmethod': 'mailed_check',
  'tenure': 10,
  'monthlycharges': 29.750000000,
  'totalcharges': 301.900000000},
 {'gender': 'female',
  'seniorcitizen': 0,
  'partner': 'yes',
  'dependents': 'no',
  'phoneservice': 'yes',
  'multiplelines': 'yes',
  'internetservice': 'fiber_optic',
  'onlinesecurity': 'no',
  'onlinebackup': 'no',
  'deviceprotection': 'yes',
  'techsupport': 'yes',
  'streamingtv': 'yes',
  'streamingmovies': 'yes',
  'contract': 'month-to-month',
  'paperlessbilling': 'yes',
  'paymentmethod': 'electronic_check',
  'tenure': 28,
  'monthlycharges': 104.800000000,
  'totalcharges': 3046.050000000},
 {'gender': 'male',
  'seniorcitizen': 0,
  'partner': 'no',
  'dependents': 'yes',
  'phoneservice': 'yes',
  'multiplelines': 'no',
  'internetservice': 'dsl',
  'onlinesecurity': 'yes',
  'onlinebackup': 'yes',
  'deviceprotection': 'no',
  'techsupport': 'no',
  'streamingtv': 'no',
  'streamingmovies': 'no',
  'contract': 'one_year',
  'paperlessbilling': 'no',
  'paymentmethod': 'bank_transfer_(automatic)',
  'tenure': 62,
  'monthlycharges': 56.150000000,
  'totalcharges': 3487.950000000},
 {'gender': 'male',
  'seniorcitizen': 0,
  'partner': 'yes',
  'dependents': 'yes',
  'phoneservice': 'yes',
  'multiplelines': 'no',
  'internetservice': 'dsl',
  'onlinesecurity': 'yes',
  'onlinebackup': 'no',
  'deviceprotection': 'no',
  'techsupport': 'no',
  'streamingtv': 'no',
  'streamingmovies': 'no',
  'contract': 'month-to-month',
  'paperlessbilling': 'yes',
  'paymentmethod': 'mailed_check',
  'tenure': 13,
  'monthlycharges': 49.950000000,
  'totalcharges': 587.450000000},
 {'gender': 'male',
  'seniorcitizen': 0,
  'partner': 'no',
  'dependents': 'no',
  'phoneservice': 'yes',
  'multiplelines': 'no',
  'internetservice': 'no',
  'onlinesecurity': 'no_internet_service',
  'onlinebackup': 'no_internet_service',
  'deviceprotection': 'no_internet_service',
  'techsupport': 'no_internet_service',
  'streamingtv': 'no_internet_service',
  'streamingmovies': 'no_internet_service',
  'contract': 'two_year',
  'paperlessbilling': 'no',
  'paymentmethod': 'credit_card_(automatic)',
  'tenure': 16,
  'monthlycharges': 18.950000000,
  'totalcharges': 326.800000000},
 {'gender': 'male',
  'seniorcitizen': 0,
  'partner': 'yes',
  'dependents': 'no',
  'phoneservice': 'yes',
  'multiplelines': 'yes',
  'internetservice': 'fiber_optic',
  'onlinesecurity': 'no',
  'onlinebackup': 'no',
  'deviceprotection': 'yes',
  'techsupport': 'no',
  'streamingtv': 'yes',
  'streamingmovies': 'yes',
  'contract': 'one_year',
  'paperlessbilling': 'no',
  'paymentmethod': 'credit_card_(automatic)',
  'tenure': 58,
  'monthlycharges': 100.350000000,
  'totalcharges': 5681.100000000},
 {'gender': 'male',
  'seniorcitizen': 0,
  'partner': 'no',
  'dependents': 'no',
  'phoneservice': 'yes',
  'multiplelines': 'yes',
  'internetservice': 'fiber_optic',
  'onlinesecurity': 'no',
  'onlinebackup': 'yes',
  'deviceprotection': 'yes',
  'techsupport': 'no',
  'streamingtv': 'yes',
  'streamingmovies': 'yes',
  'contract': 'month-to-month',
  'paperlessbilling': 'yes',
  'paymentmethod': 'bank_transfer_(automatic)',
  'tenure': 49,
  'monthlycharges': 103.700000000,
  'totalcharges': 5036.300000000},
 {'gender': 'male',
  'seniorcitizen': 0,
  'partner': 'no',
  'dependents': 'no',
  'phoneservice': 'yes',
  'multiplelines': 'no',
  'internetservice': 'fiber_optic',
  'onlinesecurity': 'yes',
  'onlinebackup': 'no',
  'deviceprotection': 'yes',
  'techsupport': 'yes',
  'streamingtv': 'yes',
  'streamingmovies': 'yes',
  'contract': 'month-to-month',
  'paperlessbilling': 'yes',
  'paymentmethod': 'electronic_check',
  'tenure': 25,
  'monthlycharges': 105.500000000,
  'totalcharges': 2686.050000000},
 {'gender': 'female',
  'seniorcitizen': 0,
  'partner': 'yes',
  'dependents': 'yes',
  'phoneservice': 'yes',
  'multiplelines': 'yes',
  'internetservice': 'fiber_optic',
  'onlinesecurity': 'yes',
  'onlinebackup': 'yes',
  'deviceprotection': 'yes',
  'techsupport': 'yes',
  'streamingtv': 'yes',
  'streamingmovies': 'yes',
  'contract': 'two_year',
  'paperlessbilling': 'no',
  'paymentmethod': 'credit_card_(automatic)',
  'tenure': 69,
  'monthlycharges': 113.250000000,
  'totalcharges': 7895.150000000},
 {'gender': 'female',
  'seniorcitizen': 0,
  'partner': 'no',
  'dependents': 'no',
  'phoneservice': 'yes',
  'multiplelines': 'no',
  'internetservice': 'no',
  'onlinesecurity': 'no_internet_service',
  'onlinebackup': 'no_internet_service',
  'deviceprotection': 'no_internet_service',
  'techsupport': 'no_internet_service',
  'streamingtv': 'no_internet_service',
  'streamingmovies': 'no_internet_service',
  'contract': 'one_year',
  'paperlessbilling': 'no',
  'paymentmethod': 'mailed_check',
  'tenure': 52,
  'monthlycharges': 20.650000000,
  'totalcharges': 1022.950000000},
 {'gender': 'male',
  'seniorcitizen': 0,
  'partner': 'no',
  'dependents': 'yes',
  'phoneservice': 'yes',
  'multiplelines': 'yes',
  'internetservice': 'fiber_optic',
  'onlinesecurity': 'yes',
  'onlinebackup': 'no',
  'deviceprotection': 'yes',
  'techsupport': 'no',
  'streamingtv': 'yes',
  'streamingmovies': 'yes',
  'contract': 'two_year',
  'paperlessbilling': 'no',
  'paymentmethod': 'bank_transfer_(automatic)',
  'tenure': 71,
  'monthlycharges': 106.700000000,
  'totalcharges': 7382.250000000},
 {'gender': 'female',
  'seniorcitizen': 0,
  'partner': 'yes',
  'dependents': 'yes',
  'phoneservice': 'yes',
  'multiplelines': 'no',
  'internetservice': 'dsl',
  'onlinesecurity': 'no',
  'onlinebackup': 'no',
  'deviceprotection': 'yes',
  'techsupport': 'yes',
  'streamingtv': 'no',
  'streamingmovies': 'no',
  'contract': 'month-to-month',
  'paperlessbilling': 'no',
  'paymentmethod': 'credit_card_(automatic)',
  'tenure': 10,
  'monthlycharges': 55.200000000,
  'totalcharges': 528.350000000},
 {'gender': 'female',
  'seniorcitizen': 0,
  'partner': 'no',
  'dependents': 'no',
  'phoneservice': 'yes',
  'multiplelines': 'no',
  'internetservice': 'fiber_optic',
  'onlinesecurity': 'no',
  'onlinebackup': 'yes',
  'deviceprotection': 'yes',
  'techsupport': 'no',
  'streamingtv': 'no',
  'streamingmovies': 'yes',
  'contract': 'month-to-month',
  'paperlessbilling': 'yes',
  'paymentmethod': 'electronic_check',
  'tenure': 21,
  'monthlycharges': 90.050000000,
  'totalcharges': 1862.900000000},
 {'gender': 'male',
  'seniorcitizen': 1,
  'partner': 'no',
  'dependents': 'no',
  'phoneservice': 'no',
  'multiplelines': 'no_phone_service',
  'internetservice': 'dsl',
  'onlinesecurity': 'no',
  'onlinebackup': 'no',
  'deviceprotection': 'yes',
  'techsupport': 'no',
  'streamingtv': 'no',
  'streamingmovies': 'yes',
  'contract': 'month-to-month',
  'paperlessbilling': 'yes',
  'paymentmethod': 'electronic_check',
  'tenure': 1,
  'monthlycharges': 39.650000000,
  'totalcharges': 39.650000000},
 {'gender': 'male',
  'seniorcitizen': 0,
  'partner': 'yes',
  'dependents': 'no',
  'phoneservice': 'yes',
  'multiplelines': 'no',
  'internetservice': 'no',
  'onlinesecurity': 'no_internet_service',
  'onlinebackup': 'no_internet_service',
  'deviceprotection': 'no_internet_service',
  'techsupport': 'no_internet_service',
  'streamingtv': 'no_internet_service',
  'streamingmovies': 'no_internet_service',
  'contract': 'one_year',
  'paperlessbilling': 'no',
  'paymentmethod': 'bank_transfer_(automatic)',
  'tenure': 12,
  'monthlycharges': 19.800000000,
  'totalcharges': 202.250000000},
 {'gender': 'male',
  'seniorcitizen': 0,
  'partner': 'no',
  'dependents': 'no',
  'phoneservice': 'yes',
  'multiplelines': 'no',
  'internetservice': 'no',
  'onlinesecurity': 'no_internet_service',
  'onlinebackup': 'no_internet_service',
  'deviceprotection': 'no_internet_service',
  'techsupport': 'no_internet_service',
  'streamingtv': 'no_internet_service',
  'streamingmovies': 'no_internet_service',
  'contract': 'month-to-month',
  'paperlessbilling': 'no',
  'paymentmethod': 'mailed_check',
  'tenure': 1,
  'monthlycharges': 20.150000000,
  'totalcharges': 20.150000000},
 {'gender': 'female',
  'seniorcitizen': 0,
  'partner': 'yes',
  'dependents': 'no',
  'phoneservice': 'yes',
  'multiplelines': 'yes',
  'internetservice': 'dsl',
  'onlinesecurity': 'no',
  'onlinebackup': 'yes',
  'deviceprotection': 'no',
  'techsupport': 'yes',
  'streamingtv': 'no',
  'streamingmovies': 'no',
  'contract': 'two_year',
  'paperlessbilling': 'yes',
  'paymentmethod': 'credit_card_(automatic)',
  'tenure': 58,
  'monthlycharges': 59.900000000,
  'totalcharges': 3505.100000000},
 {'gender': 'male',
  'seniorcitizen': 0,
  'partner': 'yes',
  'dependents': 'yes',
  'phoneservice': 'yes',
  'multiplelines': 'no',
  'internetservice': 'dsl',
  'onlinesecurity': 'yes',
  'onlinebackup': 'yes',
  'deviceprotection': 'no',
  'techsupport': 'yes',
  'streamingtv': 'no',
  'streamingmovies': 'no',
  'contract': 'month-to-month',
  'paperlessbilling': 'no',
  'paymentmethod': 'credit_card_(automatic)',
  'tenure': 49,
  'monthlycharges': 59.600000000,
  'totalcharges': 2970.300000000},
 {'gender': 'female',
  'seniorcitizen': 0,
  'partner': 'no',
  'dependents': 'no',
  'phoneservice': 'yes',
  'multiplelines': 'no',
  'internetservice': 'dsl',
  'onlinesecurity': 'yes',
  'onlinebackup': 'yes',
  'deviceprotection': 'no',
  'techsupport': 'no',
  'streamingtv': 'no',
  'streamingmovies': 'no',
  'contract': 'month-to-month',
  'paperlessbilling': 'yes',
  'paymentmethod': 'bank_transfer_(automatic)',
  'tenure': 30,
  'monthlycharges': 55.300000000,
  'totalcharges': 1530.600000000},
 {'gender': 'male',
  'seniorcitizen': 0,
  'partner': 'yes',
  'dependents': 'yes',
  'phoneservice': 'yes',
  'multiplelines': 'yes',
  'internetservice': 'fiber_optic',
  'onlinesecurity': 'no',
  'onlinebackup': 'yes',
  'deviceprotection': 'no',
  'techsupport': 'no',
  'streamingtv': 'yes',
  'streamingmovies': 'yes',
  'contract': 'month-to-month',
  'paperlessbilling': 'yes',
  'paymentmethod': 'electronic_check',
  'tenure': 47,
  'monthlycharges': 99.350000000,
  'totalcharges': 4749.150000000},
 {'gender': 'male',
  'seniorcitizen': 0,
  'partner': 'yes',
  'dependents': 'yes',
  'phoneservice': 'no',
  'multiplelines': 'no_phone_service',
  'internetservice': 'dsl',
  'onlinesecurity': 'no',
  'onlinebackup': 'yes',
  'deviceprotection': 'no',
  'techsupport': 'no',
  'streamingtv': 'no',
  'streamingmovies': 'no',
  'contract': 'month-to-month',
  'paperlessbilling': 'no',
  'paymentmethod': 'electronic_check',
  'tenure': 1,
  'monthlycharges': 30.200000000,
  'totalcharges': 30.200000000},
 {'gender': 'male',
  'seniorcitizen': 0,
  'partner': 'yes',
  'dependents': 'no',
  'phoneservice': 'yes',
  'multiplelines': 'yes',
  'internetservice': 'dsl',
  'onlinesecurity': 'yes',
  'onlinebackup': 'yes',
  'deviceprotection': 'yes',
  'techsupport': 'yes',
  'streamingtv': 'yes',
  'streamingmovies': 'yes',
  'contract': 'two_year',
  'paperlessbilling': 'yes',
  'paymentmethod': 'credit_card_(automatic)',
  'tenure': 72,
  'monthlycharges': 90.250000000,
  'totalcharges': 6369.450000000},
 {'gender': 'female',
  'seniorcitizen': 0,
  'partner': 'no',
  'dependents': 'yes',
  'phoneservice': 'yes',
  'multiplelines': 'no',
  'internetservice': 'dsl',
  'onlinesecurity': 'no',
  'onlinebackup': 'no',
  'deviceprotection': 'no',
  'techsupport': 'no',
  'streamingtv': 'yes',
  'streamingmovies': 'yes',
  'contract': 'month-to-month',
  'paperlessbilling': 'yes',
  'paymentmethod': 'mailed_check',
  'tenure': 17,
  'monthlycharges': 64.700000000,
  'totalcharges': 1093.100000000},
 {'gender': 'female',
  'seniorcitizen': 1,
  'partner': 'yes',
  'dependents': 'no',
  'phoneservice': 'yes',
  'multiplelines': 'yes',
  'internetservice': 'fiber_optic',
  'onlinesecurity': 'yes',
  'onlinebackup': 'yes',
  'deviceprotection': 'yes',
  'techsupport': 'yes',
  'streamingtv': 'no',
  'streamingmovies': 'no',
  'contract': 'two_year',
  'paperlessbilling': 'yes',
  'paymentmethod': 'credit_card_(automatic)',
  'tenure': 71,
  'monthlycharges': 96.350000000,
  'totalcharges': 6766.950000000},
 {'gender': 'male',
  'seniorcitizen': 1,
  'partner': 'yes',
  'dependents': 'no',
  'phoneservice': 'yes',
  'multiplelines': 'no',
  'internetservice': 'fiber_optic',
  'onlinesecurity': 'no',
  'onlinebackup': 'no',
  'deviceprotection': 'yes',
  'techsupport': 'no',
  'streamingtv': 'yes',
  'streamingmovies': 'yes',
  'contract': 'month-to-month',
  'paperlessbilling': 'yes',
  'paymentmethod': 'credit_card_(automatic)',
  'tenure': 2,
  'monthlycharges': 95.500000000,
  'totalcharges': 181.650000000},
 {'gender': 'female',
  'seniorcitizen': 0,
  'partner': 'yes',
  'dependents': 'yes',
  'phoneservice': 'yes',
  'multiplelines': 'no',
  'internetservice': 'dsl',
  'onlinesecurity': 'yes',
  'onlinebackup': 'yes',
  'deviceprotection': 'yes',
  'techsupport': 'yes',
  'streamingtv': 'no',
  'streamingmovies': 'no',
  'contract': 'one_year',
  'paperlessbilling': 'no',
  'paymentmethod': 'mailed_check',
  'tenure': 27,
  'monthlycharges': 66.150000000,
  'totalcharges': 1874.450000000},
 {'gender': 'male',
  'seniorcitizen': 0,
  'partner': 'no',
  'dependents': 'no',
  'phoneservice': 'yes',
  'multiplelines': 'no',
  'internetservice': 'no',
  'onlinesecurity': 'no_internet_service',
  'onlinebackup': 'no_internet_service',
  'deviceprotection': 'no_internet_service',
  'techsupport': 'no_internet_service',
  'streamingtv': 'no_internet_service',
  'streamingmovies': 'no_internet_service',
  'contract': 'month-to-month',
  'paperlessbilling': 'no',
  'paymentmethod': 'bank_transfer_(automatic)',
  'tenure': 1,
  'monthlycharges': 20.200000000,
  'totalcharges': 20.200000000},
 {'gender': 'male',
  'seniorcitizen': 1,
  'partner': 'no',
  'dependents': 'no',
  'phoneservice': 'yes',
  'multiplelines': 'no',
  'internetservice': 'dsl',
  'onlinesecurity': 'no',
  'onlinebackup': 'no',
  'deviceprotection': 'no',
  'techsupport': 'no',
  'streamingtv': 'no',
  'streamingmovies': 'no',
  'contract': 'month-to-month',
  'paperlessbilling': 'no',
  'paymentmethod': 'bank_transfer_(automatic)',
  'tenure': 1,
  'monthlycharges': 45.250000000,
  'totalcharges': 45.250000000},
 {'gender': 'female',
  'seniorcitizen': 0,
  'partner': 'yes',
  'dependents': 'yes',
  'phoneservice': 'yes',
  'multiplelines': 'yes',
  'internetservice': 'fiber_optic',
  'onlinesecurity': 'yes',
  'onlinebackup': 'yes',
  'deviceprotection': 'no',
  'techsupport': 'yes',
  'streamingtv': 'yes',
  'streamingmovies': 'no',
  'contract': 'two_year',
  'paperlessbilling': 'no',
  'paymentmethod': 'bank_transfer_(automatic)',
  'tenure': 72,
  'monthlycharges': 99.900000000,
  'totalcharges': 7251.700000000},
 {'gender': 'male',
  'seniorcitizen': 0,
  'partner': 'no',
  'dependents': 'no',
  'phoneservice': 'yes',
  'multiplelines': 'no',
  'internetservice': 'fiber_optic',
  'onlinesecurity': 'no',
  'onlinebackup': 'no',
  'deviceprotection': 'no',
  'techsupport': 'no',
  'streamingtv': 'no',
  'streamingmovies': 'no',
  'contract': 'month-to-month',
  'paperlessbilling': 'yes',
  'paymentmethod': 'electronic_check',
  'tenure': 5,
  'monthlycharges': 69.700000000,
  'totalcharges': 316.900000000},
 {'gender': 'female',
  'seniorcitizen': 0,
  'partner': 'no',
  'dependents': 'no',
  'phoneservice': 'yes',
  'multiplelines': 'no',
  'internetservice': 'fiber_optic',
  'onlinesecurity': 'no',
  'onlinebackup': 'no',
  'deviceprotection': 'yes',
  'techsupport': 'no',
  'streamingtv': 'no',
  'streamingmovies': 'no',
  'contract': 'month-to-month',
  'paperlessbilling': 'yes',
  'paymentmethod': 'credit_card_(automatic)',
  'tenure': 46,
  'monthlycharges': 74.800000000,
  'totalcharges': 3548.300000000},
 {'gender': 'male',
  'seniorcitizen': 0,
  'partner': 'no',
  'dependents': 'no',
  'phoneservice': 'yes',
  'multiplelines': 'yes',
  'internetservice': 'fiber_optic',
  'onlinesecurity': 'no',
  'onlinebackup': 'yes',
  'deviceprotection': 'yes',

In [151]:
from sklearn.feature_extraction import DictVectorizer

dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical + numerical].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

In [152]:
# fit_transform consists of 2 steps fit and tranform
# fit learns the list of categories for each column like gender has male and female
# transform turns dictionaries into a matrix 
# By default Dictvectorizer returns a sparse matrix, a data structure which stores
# only non zero values coz most of the matriz is zeroes. They are more memory
# efficient but for this dataset it is simpler to work with a dense array

# after fit_tranfrom dv has the fit which means it has learned the rules or
# how many categories are there for each columm which we can use for test
# and validation set later on so no need to perform fit there only transform

In [153]:
# To see what columns the vectorizer created, use dv.get_feature_names_out(). 
# For the full dataset we get 45 names: one column per 
# category value (contract=month-to-month, internetservice=fiber_optic, ...) 
# plus the three numerical columns. The resulting matrix has 45 columns,
# one per feature name

X_train.shape

(4225, 45)

In [154]:
# 4225 is the number of rows in training set, 45 is number of features after 
# encoding

In [155]:
# Encoding the validation set
# The validation set must be encoded in exactly the same way as the training set.
# Thats why we call only tranform on the validaton set and use the already
# fitted vectorizer 
val_dict = df_val[categorical + numerical].to_dict(orient = 'records')
X_val = dv.transform(val_dict)

In [156]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [157]:
sigmoid(-100),sigmoid(4), sigmoid(100)
# as we can see from values below for large negative numbers it tends to 0
# ans for large positive numbers it tenda to 1

(0.000000000, 0.982013790, 1.000000000)

In [158]:
w0 = 2
w = np.array([1.4,2.9,4.7])
def logistic_regresssion(xi):
    score = w0
    
    score = score + xi.dot(w)
    result = sigmoid(score)
    return result

In [159]:
# logistic_regresssion(np.array([2,4]))

# Training logistic regression

In [160]:
from sklearn.linear_model import LogisticRegression

In [161]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [162]:
model.intercept_[0]

-0.193502504

In [163]:
model.coef_[0].round(3)

array([ 0.73 , -0.001, -0.912,  0.047, -0.23 , -0.012, -0.139, -0.032,
       -0.106, -0.077, -0.365,  0.321, -0.139,  0.002, -0.18 ,  0.056,
       -0.058,  0.094, -0.139, -0.138,  0.161, -0.139, -0.205, -0.303,
        0.12 , -0.146, -0.037, -0.066, -0.202,  0.159, -0.074,  0.056,
       -0.238,  0.102, -0.129, -0.139,  0.085, -0.139, -0.139,  0.095,
        0.225, -0.139, -0.269, -0.051,  0.   ])

In [164]:
y_pred = model.predict_proba(X_val)[:,1]
y_pred

array([0.525598815, 0.670478581, 0.14395721 , ..., 0.699330877,
       0.289009116, 0.30031303 ], shape=(1409,))

In [165]:
churn_decision = (y_pred>=0.5)

In [166]:
(y_val == churn_decision).mean()

0.808374734

In [167]:
# 80% accuracy achieved

In [168]:
df_pred = pd.DataFrame()
df_pred['probability'] = y_pred
df_pred['prediction'] = churn_decision.astype(int)
df_pred['actual'] = y_val

In [169]:
df_pred['correct'] = df_pred.prediction == df_pred.actual
df_pred.correct.mean()

0.808374734

In [170]:
df_pred

      probability  prediction  actual  correct
0     0.525598815           1       1     True
1     0.670478581           1       1     True
2     0.143957210           0       0     True
3     0.006905004           0       0     True
4     0.055110901           0       0     True
...           ...         ...     ...      ...
1404  0.304367271           0       0     True
1405  0.336608629           0       0     True
1406  0.699330877           1       1     True
1407  0.289009116           0       1    False
1408  0.300313030           0       1    False

[1409 rows x 4 columns]

In [171]:
dict(zip(dv.get_feature_names_out(), model.coef_[0].round(3)))

{'contract=month-to-month': 0.730000000,
 'contract=one_year': -0.001000000,
 'contract=two_year': -0.912000000,
 'dependents=no': 0.047000000,
 'dependents=yes': -0.230000000,
 'deviceprotection=no': -0.012000000,
 'deviceprotection=no_internet_service': -0.139000000,
 'deviceprotection=yes': -0.032000000,
 'gender=female': -0.106000000,
 'gender=male': -0.077000000,
 'internetservice=dsl': -0.365000000,
 'internetservice=fiber_optic': 0.321000000,
 'internetservice=no': -0.139000000,
 'monthlycharges': 0.002000000,
 'multiplelines=no': -0.180000000,
 'multiplelines=no_phone_service': 0.056000000,
 'multiplelines=yes': -0.058000000,
 'onlinebackup=no': 0.094000000,
 'onlinebackup=no_internet_service': -0.139000000,
 'onlinebackup=yes': -0.138000000,
 'onlinesecurity=no': 0.161000000,
 'onlinesecurity=no_internet_service': -0.139000000,
 'onlinesecurity=yes': -0.205000000,
 'paperlessbilling=no': -0.303000000,
 'paperlessbilling=yes': 0.120000000,
 'partner=no': -0.146000000,
 'partner=yes': -0.037000000,
 'paymentmethod=bank_transfer_(automatic)': -0.066000000,
 'paymentmethod=credit_card_(automatic)': -0.202000000,
 'paymentmethod=electronic_check': 0.159000000,
 'paymentmethod=mailed_check': -0.074000000,
 'phoneservice=no': 0.056000000,
 'phoneservice=yes': -0.238000000,
 'seniorcitizen': 0.102000000,
 'streamingmovies=no': -0.129000000,
 'streamingmovies=no_internet_service': -0.139000000,
 'streamingmovies=yes': 0.085000000,
 'streamingtv=no': -0.139000000,
 'streamingtv=no_internet_service': -0.139000000,
 'streamingtv=yes': 0.095000000,
 'techsupport=no': 0.225000000,
 'techsupport=no_internet_service': -0.139000000,
 'techsupport=yes': -0.269000000,
 'tenure': -0.051000000,
 'totalcharges': 0.000000000}

In [172]:
dicts_full_train = df_full_train[categorical + numerical].to_dict(orient ='records')

dv = DictVectorizer(sparse = False)
X_full_train = dv.fit_transform(dicts_full_train)

y_full_train = df_full_train.churn.values

In [175]:
model = LogisticRegression(max_iter=1000)
model.fit(X_full_train,y_full_train)

LogisticRegression(max_iter=1000)

In [179]:
dicts_test = df_test[categorical+numerical].to_dict(orient = 'records')
X_test = dv.transform(dicts_test) # we only use tranform not fit transform

y_pred = model.predict_proba(X_test)[:,1]
churn_decision = (y_pred>=0.5)
(churn_decision == y_test).mean()

0.806955287

In [180]:
# 80.6 % accuracy is good and is close to that on validation
customer = dicts_test[-1]
customer

{'gender': 'male',
 'seniorcitizen': 0,
 'partner': 'yes',
 'dependents': 'no',
 'phoneservice': 'yes',
 'multiplelines': 'no',
 'internetservice': 'dsl',
 'onlinesecurity': 'no',
 'onlinebackup': 'yes',
 'deviceprotection': 'yes',
 'techsupport': 'no',
 'streamingtv': 'no',
 'streamingmovies': 'no',
 'contract': 'month-to-month',
 'paperlessbilling': 'yes',
 'paymentmethod': 'mailed_check',
 'tenure': 8,
 'monthlycharges': 54.750000000,
 'totalcharges': 445.850000000}

In [188]:
X_small = dv.transform([customer])
model.predict_proba(X_small)[0,1]

0.329731247

In [187]:
y_test.iloc[-1]

np.int64(0)